[package]
name = "otltool"
version = "0.1.0"
authors = ["Risto Saarelma"]
license = "MIT OR Apache-2.0"
edition = "2018"

[workspace]
members = ["parser"]

[dependencies]
chrono = "0.4"
csv = "1"
log = "0.4"
md5 = "0.7"
parser = { path = "parser" }
reqwest = { version = "0.10", features = ["blocking", "json"] }
ron = "0.5"
select = "0.4"
serde = "1"
structopt = "0.3"
url = "1"
walkdir = "2"
