[package]
name = "otltool"
version = "0.1.0"
authors = ["Risto Saarelma"]
license = "MIT OR Apache-2.0"
edition = "2018"

[workspace]
members = ["parser", "wasm" ]

[dependencies]
md5 = "0.6"
parser = { path = "parser" }
ron = "0.5"
serde = "1"
structopt = "0.2"
walkdir = "2"
