[package]
name = "otltool"
version = "0.1.0"
authors = ["Risto Saarelma"]
license = "MIT OR Apache-2.0"
edition = "2018"

[workspace]
members = ["parser", "scraper", "anki-connect"]

[dependencies]
chrono = "0.4"
env_logger = "0.7"
log = "0.4"
md5 = "0.7"
parser = { path = "parser" }
ron = "0.5"
scraper = { path = "scraper" }
serde = "1"
structopt = "0.3"
walkdir = "2"
