[package]
name = "otltool"
version = "0.1.0"
authors = ["Risto Saarelma"]
license = "MIT OR Apache-2.0"
edition = "2018"

[workspace]
members = ["parser", "wasm" ]

[dependencies]
parser = { path = "parser" }
structopt = "0.2"
