[package]
name = "parser"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
edition = "2018"

[dependencies]
deunicode = "1"
log = "0.4"
md5 = "0.7"
nom = "5"
ron = "0.5"
serde = "1"

[dev-dependencies]
env_logger = "0.7"
pretty_assertions = "0.6"
